#!/usr/bin/env python3
"""Auto-discover assets in resources/webp/ and generate build artifacts.

Convention:
  {brand}_boot.webp      → boot animation for brand (selected by Kconfig)
  {brand}_boot_2x.webp   → 2x boot animation for brand
  {name}.webp            → common asset (shared across brands)
  {name}_2x.webp         → 2x common asset

Generates:
  asset_data.h       — #include directives with Kconfig conditionals
  asset_registry.inc — embedded_asset_t entries for the registry array

Usage: python3 generate_assets.py <webp_dir> <output_dir>
"""

import glob
import os
import re
import sys


def webp_to_symbol(name: str) -> str:
    """Derive C symbol from asset name. e.g. 'config' → 'ASSET_CONFIG_WEBP'."""
    return f"ASSET_{name.upper()}_WEBP"


def main():
    webp_dir = sys.argv[1]
    output_dir = sys.argv[2]
    os.makedirs(output_dir, exist_ok=True)

    # Discover all webp files
    webps = sorted(glob.glob(os.path.join(webp_dir, "*.webp")))
    if not webps:
        print(f"ERROR: No .webp files found in {webp_dir}", file=sys.stderr)
        sys.exit(1)

    # Categorize
    boot_brands_1x = {}  # brand → filename stem
    boot_brands_2x = {}  # brand → filename stem
    common_1x = {}       # name → filename stem
    common_2x = {}       # name → filename stem

    for path in webps:
        stem = os.path.basename(path).replace(".webp", "")

        if stem.endswith("_boot_2x"):
            brand = stem.replace("_boot_2x", "")
            boot_brands_2x[brand] = stem
        elif stem.endswith("_boot"):
            brand = stem.replace("_boot", "")
            boot_brands_1x[brand] = stem
        elif stem.endswith("_2x"):
            name = stem.replace("_2x", "")
            common_2x[name] = stem
        else:
            common_1x[stem] = stem

    # The "default" boot brand is the first one that isn't explicitly a Kconfig choice
    # Convention: tronbyt is the default (fallback in #else)
    default_boot = "tronbyt"

    # ── Generate asset_data.h ─────────────────────────────────────────
    lines = [
        "// Auto-generated by tools/generate_assets.py — do not edit.",
        "// Boot animation selected by Kconfig. Resolution by panel size.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#include \"sdkconfig.h\"",
        "",
        "// ── Boot animation ──────────────────────────────────────────────",
    ]

    # Build #if / #elif / #else chain for boot brands
    non_default = [b for b in sorted(boot_brands_1x.keys()) if b != default_boot]
    first = True
    for brand in non_default:
        kconfig = f"CONFIG_BOOT_WEBP_{brand.upper()}"
        directive = "#if" if first else "#elif"
        lines.append(f"{directive} {kconfig}")

        # Check if 2x exists for this brand
        if brand in boot_brands_2x:
            lines.append(f"#  if CONFIG_HUB75_PANEL_WIDTH >= 128")
            lines.append(f"#  include \"{boot_brands_2x[brand].replace('-', '_')}_c\"")
            lines.append(f"#  else")
            lines.append(f"#  include \"{boot_brands_1x[brand].replace('-', '_')}_c\"")
            lines.append(f"#  endif")
        else:
            lines.append(f"#include \"{boot_brands_1x[brand].replace('-', '_')}_c\"")
        first = False

    # Default brand
    if non_default:
        lines.append("#else")
    if default_boot in boot_brands_2x:
        lines.append(f"#  if CONFIG_HUB75_PANEL_WIDTH >= 128")
        lines.append(f"#  include \"{boot_brands_2x[default_boot].replace('-', '_')}_c\"")
        lines.append(f"#  else")
        lines.append(f"#  include \"{boot_brands_1x[default_boot].replace('-', '_')}_c\"")
        lines.append(f"#  endif")
    elif default_boot in boot_brands_1x:
        lines.append(f"#include \"{boot_brands_1x[default_boot].replace('-', '_')}_c\"")
    if non_default:
        lines.append("#endif")

    # Common assets with 2x resolution switching
    lines.append("")
    lines.append("// ── Common assets ───────────────────────────────────────────────")

    # Check if any 2x common assets exist
    has_2x = bool(common_2x)

    if has_2x:
        lines.append("#if CONFIG_HUB75_PANEL_WIDTH >= 128")
        for name in sorted(common_2x.keys()):
            c_file = common_2x[name].replace("-", "_") + "_c"
            lines.append(f"#include \"{c_file}\"")
        lines.append("#else")

    for name in sorted(common_1x.keys()):
        c_file = common_1x[name].replace("-", "_") + "_c"
        lines.append(f"#include \"{c_file}\"")

    if has_2x:
        lines.append("#endif")

    lines.append("")

    header_path = os.path.join(output_dir, "asset_data.h")
    with open(header_path, "w") as f:
        f.write("\n".join(lines))
    print(f"Generated {header_path}")

    # ── Generate asset_registry.inc ───────────────────────────────────
    # Registry entries for assets.cpp
    registry = [
        "// Auto-generated by tools/generate_assets.py — do not edit.",
    ]

    # Boot is always ASSET_BOOT_WEBP
    registry.append('{"boot", ASSET_BOOT_WEBP, ASSET_BOOT_WEBP_LEN},')

    # Common assets — derive symbol from name
    for name in sorted(common_1x.keys()):
        symbol = webp_to_symbol(name)
        registry.append(f'{{\"{name}\", {symbol}, {symbol}_LEN}},')

    registry_path = os.path.join(output_dir, "asset_registry.inc")
    with open(registry_path, "w") as f:
        f.write("\n".join(registry))
    print(f"Generated {registry_path}")

    # ── Print conversion jobs (for CMake to parse) ────────────────────
    # Format: webp_filename:c_filename:symbol
    all_jobs = []

    # Boot brands (all need converting, Kconfig selects at compile time)
    for brand, stem in sorted(boot_brands_1x.items()):
        c_name = stem.replace("-", "_") + "_c"
        all_jobs.append(f"{stem}.webp:{c_name}:ASSET_BOOT_WEBP")
    for brand, stem in sorted(boot_brands_2x.items()):
        c_name = stem.replace("-", "_") + "_c"
        all_jobs.append(f"{stem}.webp:{c_name}:ASSET_BOOT_WEBP")

    # Common assets
    for name, stem in sorted(common_1x.items()):
        c_name = stem.replace("-", "_") + "_c"
        symbol = webp_to_symbol(name)
        all_jobs.append(f"{stem}.webp:{c_name}:{symbol}")
    for name, stem in sorted(common_2x.items()):
        c_name = stem.replace("-", "_") + "_c"
        symbol = webp_to_symbol(name.replace("_2x", ""))
        all_jobs.append(f"{stem}.webp:{c_name}:{symbol}")

    # Write jobs list for CMake
    jobs_path = os.path.join(output_dir, "asset_jobs.txt")
    with open(jobs_path, "w") as f:
        for job in all_jobs:
            f.write(job + "\n")
    print(f"Generated {jobs_path} ({len(all_jobs)} assets)")


if __name__ == "__main__":
    main()
